# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import ttc_pb2 as ttc__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in ttc_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RouteListServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetRouteList = channel.unary_unary(
                '/ttc.RouteListService/GetRouteList',
                request_serializer=ttc__pb2.RouteListRequest.SerializeToString,
                response_deserializer=ttc__pb2.RouteListResponse.FromString,
                _registered_method=True)


class RouteListServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetRouteList(self, request, context):
        """Fetch the list of routes for the agency
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RouteListServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetRouteList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRouteList,
                    request_deserializer=ttc__pb2.RouteListRequest.FromString,
                    response_serializer=ttc__pb2.RouteListResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ttc.RouteListService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ttc.RouteListService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RouteListService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetRouteList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ttc.RouteListService/GetRouteList',
            ttc__pb2.RouteListRequest.SerializeToString,
            ttc__pb2.RouteListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class RouteConfigServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetRouteConfig = channel.unary_unary(
                '/ttc.RouteConfigService/GetRouteConfig',
                request_serializer=ttc__pb2.RouteConfigRequest.SerializeToString,
                response_deserializer=ttc__pb2.RouteConfigResponse.FromString,
                _registered_method=True)


class RouteConfigServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetRouteConfig(self, request, context):
        """Fetch details for a specific route
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RouteConfigServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetRouteConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRouteConfig,
                    request_deserializer=ttc__pb2.RouteConfigRequest.FromString,
                    response_serializer=ttc__pb2.RouteConfigResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ttc.RouteConfigService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ttc.RouteConfigService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RouteConfigService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetRouteConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ttc.RouteConfigService/GetRouteConfig',
            ttc__pb2.RouteConfigRequest.SerializeToString,
            ttc__pb2.RouteConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class PredictionsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPrediction = channel.unary_unary(
                '/ttc.PredictionsService/GetPrediction',
                request_serializer=ttc__pb2.PredictionRequest.SerializeToString,
                response_deserializer=ttc__pb2.PredictionResponse.FromString,
                _registered_method=True)


class PredictionsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetPrediction(self, request, context):
        """Fetch prediction for next vehicle arrival
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PredictionsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPrediction': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPrediction,
                    request_deserializer=ttc__pb2.PredictionRequest.FromString,
                    response_serializer=ttc__pb2.PredictionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ttc.PredictionsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ttc.PredictionsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PredictionsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetPrediction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ttc.PredictionsService/GetPrediction',
            ttc__pb2.PredictionRequest.SerializeToString,
            ttc__pb2.PredictionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
