# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ttc.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'ttc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tttc.proto\x12\x03ttc\"&\n\x10RouteListRequest\x12\x12\n\nagency_tag\x18\x01 \x01(\t\"/\n\x11RouteListResponse\x12\x1a\n\x06routes\x18\x01 \x03(\x0b\x32\n.ttc.Route\".\n\x05Route\x12\x11\n\troute_tag\x18\x01 \x01(\t\x12\x12\n\nroute_name\x18\x02 \x01(\t\";\n\x12RouteConfigRequest\x12\x12\n\nagency_tag\x18\x01 \x01(\t\x12\x11\n\troute_tag\x18\x02 \x01(\t\">\n\x13RouteConfigResponse\x12\'\n\ndirections\x18\x01 \x03(\x0b\x32\x13.ttc.RouteDirection\"w\n\x0eRouteDirection\x12\x15\n\rdirection_tag\x18\x01 \x01(\t\x12\x17\n\x0f\x64irection_title\x18\x02 \x01(\t\x12\x16\n\x0e\x64irection_name\x18\x03 \x01(\t\x12\x1d\n\x05stops\x18\x04 \x03(\x0b\x32\x0e.ttc.RouteStop\"A\n\tRouteStop\x12\x0f\n\x07stop_id\x18\x01 \x01(\t\x12\x11\n\tstop_name\x18\x02 \x01(\t\x12\x10\n\x08stop_tag\x18\x03 \x01(\t\"K\n\x11PredictionRequest\x12\x12\n\nagency_tag\x18\x01 \x01(\t\x12\x0f\n\x07stop_id\x18\x02 \x01(\t\x12\x11\n\troute_tag\x18\x03 \x01(\t\"D\n\x12PredictionResponse\x12.\n\x10next_bus_arrival\x18\x01 \x03(\x0b\x32\x14.ttc.PredictionFinal\">\n\x0fPredictionFinal\x12\x17\n\x0f\x64irection_title\x18\x01 \x01(\t\x12\x12\n\nprediction\x18\x02 \x01(\t2Q\n\x10RouteListService\x12=\n\x0cGetRouteList\x12\x15.ttc.RouteListRequest\x1a\x16.ttc.RouteListResponse2Y\n\x12RouteConfigService\x12\x43\n\x0eGetRouteConfig\x12\x17.ttc.RouteConfigRequest\x1a\x18.ttc.RouteConfigResponse2V\n\x12PredictionsService\x12@\n\rGetPrediction\x12\x16.ttc.PredictionRequest\x1a\x17.ttc.PredictionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ttc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ROUTELISTREQUEST']._serialized_start=18
  _globals['_ROUTELISTREQUEST']._serialized_end=56
  _globals['_ROUTELISTRESPONSE']._serialized_start=58
  _globals['_ROUTELISTRESPONSE']._serialized_end=105
  _globals['_ROUTE']._serialized_start=107
  _globals['_ROUTE']._serialized_end=153
  _globals['_ROUTECONFIGREQUEST']._serialized_start=155
  _globals['_ROUTECONFIGREQUEST']._serialized_end=214
  _globals['_ROUTECONFIGRESPONSE']._serialized_start=216
  _globals['_ROUTECONFIGRESPONSE']._serialized_end=278
  _globals['_ROUTEDIRECTION']._serialized_start=280
  _globals['_ROUTEDIRECTION']._serialized_end=399
  _globals['_ROUTESTOP']._serialized_start=401
  _globals['_ROUTESTOP']._serialized_end=466
  _globals['_PREDICTIONREQUEST']._serialized_start=468
  _globals['_PREDICTIONREQUEST']._serialized_end=543
  _globals['_PREDICTIONRESPONSE']._serialized_start=545
  _globals['_PREDICTIONRESPONSE']._serialized_end=613
  _globals['_PREDICTIONFINAL']._serialized_start=615
  _globals['_PREDICTIONFINAL']._serialized_end=677
  _globals['_ROUTELISTSERVICE']._serialized_start=679
  _globals['_ROUTELISTSERVICE']._serialized_end=760
  _globals['_ROUTECONFIGSERVICE']._serialized_start=762
  _globals['_ROUTECONFIGSERVICE']._serialized_end=851
  _globals['_PREDICTIONSSERVICE']._serialized_start=853
  _globals['_PREDICTIONSSERVICE']._serialized_end=939
# @@protoc_insertion_point(module_scope)
